[package]
name = "auth-core-github"
description = "GitHub OAuth login provider for auth-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
auth-core = { path = "../auth-core", version = "0.1.0" }
anyhow = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
